# Generated by Django 5.2.4 on 2025-07-28 15:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bug', 'Bug de Seguridad'), ('acceso_no_autorizado', 'Acceso No Autorizado'), ('phishing', 'Intento de Phishing'), ('malware', 'Detección de Malware'), ('fuga_datos', 'Fuga de Datos'), ('vulnerabilidad', 'Vulnerabilidad del Sistema'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de Incidente')),
                ('descripcion', models.TextField(help_text='Describa detalladamente el incidente de seguridad', verbose_name='Descripción del Incidente')),
                ('fecha_reporte', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Reporte')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('gravedad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20, verbose_name='Gravedad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('notas_internas', models.TextField(blank=True, help_text='Notas para uso interno del equipo de seguridad', null=True, verbose_name='Notas Internas')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes_reportados', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
