# Generated by Django 5.2.4 on 2025-07-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='fecha_reporte',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reporte'),
        ),
    ]
