# Generated by Django 5.2.4 on 2025-08-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0002_alter_incidente_fecha_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='notas_internas',
            field=models.TextField(blank=True, help_text='Notas para uso interno del equipo de seguridad', verbose_name='Notas Internas'),
        ),
    ]
