# Generated by Django 5.2.4 on 2025-08-03 05:04

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0003_alter_incidente_notas_internas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='descripcion',
            field=encrypted_model_fields.fields.EncryptedTextField(help_text='Describa detalladamente el incidente de seguridad', verbose_name='Descripción del Incidente'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='gravedad',
            field=encrypted_model_fields.fields.EncryptedTextField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', verbose_name='Gravedad'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='tipo',
            field=encrypted_model_fields.fields.EncryptedTextField(choices=[('bug', 'Bug de Seguridad'), ('acceso_no_autorizado', 'Acceso No Autorizado'), ('phishing', 'Intento de Phishing'), ('malware', 'Detección de Malware'), ('fuga_datos', 'Fuga de Datos'), ('vulnerabilidad', 'Vulnerabilidad del Sistema'), ('otro', 'Otro')], verbose_name='Tipo de Incidente'),
        ),
    ]
