# Generated by Django 5.2.4 on 2025-08-04 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0004_alter_incidente_descripcion_alter_incidente_gravedad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambioIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_modificado', models.CharField(max_length=50, verbose_name='Campo modificado')),
                ('valor_anterior', models.TextField(blank=True, verbose_name='Valor anterior')),
                ('valor_nuevo', models.TextField(blank=True, verbose_name='Valor nuevo')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del cambio')),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='incidentes.incidente', verbose_name='Incidente')),
                ('usuario_modificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el cambio')),
            ],
            options={
                'verbose_name': 'Historial de Cambio',
                'verbose_name_plural': 'Historial de Cambios',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
