# Generated by Django 5.2.4 on 2025-08-02 20:17

import accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usuario_managers_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=accounts.fields.EncryptedCharField(blank=True, max_length=1600, null=True),
        ),
    ]
