# Generated by Django 5.2.4 on 2025-08-02 20:26

import accounts.fields
import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', accounts.models.UsuarioManager()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=accounts.fields.EncryptedCharField(blank=True, max_length=1600, null=True),
        ),
    ]
