# Generated by Django 5.2.4 on 2025-08-03 03:49

import accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=accounts.fields.EncryptedCharField(blank=True, max_length=1600, null=True),
        ),
    ]
